### PR TITLE
port to linux

### PR DESCRIPTION
**Pull request by madnight**

### CODE REVIEW

**Comment by madnight** [comment]
may need some cleanup and it should be checked if it still compiles under windows, at least for linux this works now

**Comment by lafreak** [comment]
Damn, this \r\n / \n line ending problem....

**Comment by lafreak** [comment]
Check if it works for you, I'll merge if its ok

**Comment by madnight** [comment]
yup still works with https://github.com/lafreak/BangoLightClient/pull/1/commits/030441db3f75af6cf80d7afee859ea9b2c5dc8aa

**Pull request merged**
