### PR TITLE
add linux fix for gethostbyname

### PR DESCRIPTION
**Pull request by madnight**
the port to linux pull request worked, but i think the merge with the new hostname feature somehow messed up the linux make, this fixes it

### CODE REVIEW

**Comment by madnight** [comment]
the other thing was a double declaration of *he that g++ complains about
```
g++ -w -fpermissive -pthread -std=c++11 -o bango BangoLightClient/Client.cpp BangoLightClient/KSocket.cpp
BangoLightClient/KSocket.cpp: In static member function ‘static bool KSocket::Connect(std::__cxx11::string, WORD)’:
BangoLightClient/KSocket.cpp:54:18: error: redeclaration of ‘hostent* he’
  struct hostent *he;
                  ^~
BangoLightClient/KSocket.cpp:48:18: note: ‘hostent* he’ previously declared here
  struct hostent *he;
```

**Comment by lafreak** [comment]
Yes my bad, try now?

**Comment by madnight** [comment]
ah okay so we had it twice?

**Comment by lafreak** [comment]
Yes, by mistake. :P

**Comment by madnight** [comment]
maybe you should not make merge requests to my fork, this might lead to confusion ^^

**Comment by lafreak** [comment]
Nah, I fixed it here and it's possible to one click merge with lafreak:master, just check if it works now for you and I'll merge it

**Comment by madnight** [comment]
works

**Pull request merged**
